apiVersion: v2
appVersion: v3.1.4
description: |
  A Helm chart for running Fairwinds Goldilocks. See https://github.com/FairwindsOps/goldilocks
icon: https://raw.githubusercontent.com/FairwindsOps/charts/master/stable/goldilocks/icon.png
keywords:
- goldilocks
- resources
- kubernetes
maintainers:
- name: sudermanjr
- name: lucasreed
name: goldilocks
sources:
- https://github.com/FairwindsOps/goldilocks
version: 3.2.1
