# Метки объектов кластера Kubernetes, используются в описании Deployment и Service. Service балансирует трафик между репликами по этим меткам.
# Переменная app устанавливается равной имени проекта разработки в Gitlab, group - равной имени группы-подгруппы проектов разработки в Gitlab.
labels:
  app: ""
  group: ""
#========

#### SERVICE ####
# Метаданные для мониторинга. Если приложение отдает свои метрики в формате Prometheus, переменную enable необходимо определить в "true"
# и в переменной metrics_path указать локацию метрик.
ingress:
  class: nginx
  location: "/"
