apiVersion: v1
kind: Secret
metadata:
  name: grafana-kubegraf-secret
  namespace: projects-accounts
  annotations:
    kubernetes.io/service-account.name: grafana-kubegraf
type: kubernetes.io/service-account-token
