apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: victoria-metrics-cluster-frontend
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
{{- with .Values.ingress.annotations }}
{{ toYaml .| indent 4 }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.location | quote }}
        pathType: Prefix
        backend:
          service:
            name: victoria-metrics-cluster-frontend
            port:
              number: 8080
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
