apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics-cluster-frontend
  labels:
    app: nginx
    app.kubernetes.io/instance: victoria-metrics-cluster
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
    app.kubernetes.io/instance: victoria-metrics-cluster
  type: ClusterIP
