kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: unrestricted-clusterrole-rb
  namespace: logging
roleRef:
  kind: ClusterRole
  name: unrestricted-clusterrole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:authenticated